[tools]
go = "1.25.4"
node = "24.10.0"
java = "adoptopenjdk-24.0.1+9"
awscli = "2.31.32"
direnv = "2.37.1"
lazygit = "0.56.0"
github-cli = "2.83.0"
usage = "2.6.0"
maven = "3.9.11"
yq = "4.48.1"
eza = "0.23.4"
dotnet = "9.0.306"
trivy = "0.67.2"
neovim = "0.11.5"
flutter = "3.35.7-stable"
dart = "3.9.4"
cmake = "4.1.2"
gradle = "9.2"

[settings]
fetch_remote_versions_cache = "365d"
always_keep_download = true
always_keep_install = true
plugin_autoupdate_last_check_duration = "365d"
quiet = true
