[tools]
go = "1.25.4"
node = "24.10.0"
java = "adoptopenjdk-24.0.1+9"
awscli = "2.32.1"
direnv = "2.37.1"
lazygit = "0.56.0"
github-cli = "2.83.1"
usage = "2.8.0"
maven = "3.9.11"
yq = "4.48.2"
eza = "0.23.4"
dotnet = "10.0.100"
trivy = "0.67.2"
neovim = "0.11.5"
flutter = "3.38.2-stable"
dart = "3.10.1"
cmake = "4.2.0"
gradle = "9.2"

[settings]
fetch_remote_versions_cache = "365d"
always_keep_download = true
always_keep_install = true
plugin_autoupdate_last_check_duration = "365d"
quiet = true
