[tools]
go = "1.26.0"
node = "25.6.1"
java = "adoptopenjdk-24.0.1+9"
awscli = "2.33.19"
direnv = "2.37.1"
lazygit = "0.56.0"
github-cli = "2.86.0"
usage = "2.16.1"
maven = "3.9.12"
yq = "4.52.2"
eza = "0.23.4"
dotnet = "10.0.102"
trivy = "0.69.1"
neovim = "0.11.6"
cmake = "4.2.3"
gradle = "9.3"
glab = "1.82.0"

[settings]
fetch_remote_versions_cache = "365d"
always_keep_download = true
always_keep_install = true
plugin_autoupdate_last_check_duration = "365d"
quiet = true
